/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static void main(String[] args) {



    }
    static int Rolling-Dice(){

        return 0;
    }
}
