/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.*;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
//    static ArrayList <String> content = new ArrayList<String>;
    static ArrayList<String> content = new ArrayList<>();
public static void test(String path) throws FileNotFoundException {
    try {


    File file = new File(path);
    Scanner scan = new Scanner(file);
    int e=1;
    while (scan.hasNextLine()){
        String check=scan.nextLine();
        if (!check.endsWith(";"))
            if(check.isEmpty() || check.endsWith("{") ||
                    check.endsWith("}") || check.contains("if") || check.contains("else"))
                System.out.print("");
            else{
                content.add("Line "+e+": Missing semicolon.");
                System.out.println("Line "+e+": Missing semicolon.");}
        ++e;
    }}
    catch (IOException e){
        System.out.println(e);
    }



}
    public static void main(String[] args) throws FileNotFoundException {
test("/Users/ahmad/java-fundamentals/java-fundamentals/linter/app/src/test/resources/oneError.js");

        }

    }

